herb_medicine_samples = [
    "Tôi muốn mua sản phẩm **dạng uống** để tặng người yêu vào ngày Valentine, bạn có loại nào có tác dụng thư giãn và tạo cảm giác ấm áp không?",
    "Có sản phẩm **dạng uống** nào phù hợp để biếu tặng sếp nhân dịp Tết Nguyên Đán, thể hiện sự kính trọng và lời chúc sức khỏe không?",
    "Tôi cần một hộp **trà pha sẵn** để chúc mừng bạn mới khai trương cửa hàng, bạn có gợi ý loại nào mang ý nghĩa may mắn và thịnh vượng không?",
    "Bạn có sản phẩm **trà** nào phù hợp để tặng mẹ nhân ngày của Mẹ, tốt cho sức khỏe và giúp ngủ ngon không?",
    "Tôi muốn mua **trà** để tri ân thầy cô vào ngày Nhà giáo Việt Nam, có loại nào có ý nghĩa về sự biết ơn và tôn trọng không?",
    "Có loại **trà** nào thích hợp để chúc mừng sinh nhật bạn bè, có hương vị dễ chịu và tốt cho sức khỏe không?",
    "Tôi cần mua **lá xông** để viếng đám tang, có loại nào thể hiện sự trang trọng và thành kính phân ưu không?",
    "Bạn có thể giới thiệu **trà** có hương vị ngọt ngào và dễ chịu để tặng người yêu nhân dịp kỷ niệm không?",
    "Tôi muốn mua **trà** đặc biệt để tặng vào ngày Quốc tế Phụ Nữ, bạn có loại nào tốt cho sức khỏe và sắc đẹp không?",
    "Loại **trà** nào phù hợp để chúc mừng tốt nghiệp, mang ý nghĩa về sự khởi đầu mới và thành công?",
    "Tôi muốn đặt một hộp **trà** để chúc mừng công ty mới thành lập, bạn có mẫu nào trang trọng và thể hiện sự phát triển không?",
    "Bạn có **trà** để làm quà tặng sinh nhật không, có hương thơm tinh tế và sang trọng?",
    "Tôi cần mua **trà** (nếu có) cho ngày kỷ niệm cưới, bạn có loại nào đặc biệt và lãng mạn không?",
    "Có **trà** nào phù hợp để thưởng thức vào dịp Tết Trung Thu, mang hương vị truyền thống và ấm cúng không?",
    "Có hộp **trà** nào dễ thương để tặng sinh nhật bé gái không, có hương vị ngọt ngào và tốt cho tiêu hóa?",
    "Tôi muốn mua **viên uống** dành tặng bà nhân ngày lễ lớn, có loại nào tốt cho sức khỏe tim mạch và trí nhớ của người lớn tuổi không?",
    "Bạn có thể làm một hộp **trà** kiểu cổ điển để biếu tặng người lớn tuổi không, có hương vị quen thuộc và tốt cho xương khớp?",
    "Tôi cần các mẫu **trà** để trang trí bàn tiệc cưới, bạn có loại nào có màu sắc đẹp và mang ý nghĩa về sự gắn kết không?",
    "**Trà** loại nào phù hợp để tặng đồng nghiệp trong dịp sinh nhật, giúp giảm căng thẳng và tăng cường năng lượng?",
    "Tôi muốn một hộp **trà** lãng mạn để tặng vợ nhân kỷ niệm ngày cưới, có hương thơm quyến rũ và giúp thư giãn?",
    "Tôi cần **trà** để thưởng thức trong một sự kiện lớn, bạn có loại nào phù hợp với số lượng đông người và dễ pha chế không?",
    "**Trà** loại nào phù hợp để gửi tặng người thân đang nằm viện, giúp an thần và tăng cường sức đề kháng?",
    "Tôi muốn đặt một hộp **trà** để chúc Tết ông bà, bạn có gợi ý nào về hương vị truyền thống không?",
    "Có loại **trà** nào phù hợp để tặng sinh nhật bạn mà trông nhẹ nhàng và tinh tế, có hương vị thanh mát không?",
    "**Trà** loại nào thích hợp để chúc mừng bạn mới sinh con, giúp phục hồi sức khỏe cho mẹ và tốt cho em bé?",
    "Tôi muốn đặt **trà** cho lễ kỷ niệm thành lập công ty, có mẫu nào thể hiện sự phát triển, thịnh vượng và sự trường tồn không?",
    "Có thể làm một hộp **trà** theo yêu cầu với màu sắc chủ đạo là [màu sắc] không, và có ý nghĩa phù hợp với dịp tặng?",
    "Tôi muốn mua **trà** để tặng cho ông bà nhân ngày lễ Vu Lan, thể hiện lòng hiếu thảo và mong muốn an lạc?",
    "**Trà** loại nào thường được dùng để tặng trong dịp lễ Phật Đản cho người lớn tuổi, mang ý nghĩa về sự thanh tịnh và bình an?",
    "Tôi cần các mẫu **trà** để tặng đồng nghiệp trong lễ kỷ niệm công ty, có loại nào thể hiện sự đoàn kết, gắn bó và tinh thần đồng đội không?",
    "Có hộp **trà** nào phù hợp để gửi tặng người thân đang ở xa quê hương không, mang hương vị quê nhà và giúp ấm lòng?",
    "Tôi muốn **trà** để tặng người bạn thân lâu ngày gặp lại, có hương vị quen thuộc và gợi nhớ kỷ niệm?",
    "Có loại **trà** nào mang ý nghĩa may mắn và tài lộc cho dịp Tết không, có màu sắc tươi tắn và hương vị đặc trưng?",
    "**Trà** loại nào đẹp và ý nghĩa để tặng mẹ vào sinh nhật, có hương thơm dịu dàng và tốt cho sức khỏe phụ nữ?",
    "Tôi muốn một hộp **trà** để tặng bạn gái, bạn có gợi ý nào về cách trang trí lãng mạn và tinh tế không?",
    "Có loại **trà túi lọc** nào dễ bảo quản để làm quà tặng đi xa không, và vẫn giữ được hương vị và chất lượng tốt?",
    "Tôi muốn đặt **trà** cho lễ hội mùa xuân, có loại nào mang hương vị tươi mới, tràn đầy năng lượng và lạc quan không?",
    "**Trà** loại nào thích hợp để tặng vào lễ Phật Đản cho người lớn tuổi, mang ý nghĩa về sự an lạc và giải thoát?",
    "Tôi cần một hộp **trà** để chúc mừng bạn mở cửa hàng mới, có loại nào mang ý nghĩa về sự phát triển và thành công bền vững?",
    "Có hộp **trà** nào độc đáo để chúc mừng sinh nhật đồng nghiệp không, có hương vị đặc biệt và thể hiện sự quan tâm?",
    "**Trà** loại nào phù hợp để tặng vợ nhân ngày Phụ nữ, giúp làm đẹp da, thư giãn và tăng cường sức khỏe?",
    "Tôi muốn đặt **trà** cho buổi họp mặt cuối năm, bạn có gợi ý gì về không gian ấm cúng không?",
    "Có loại **trà** nào tượng trưng cho sự thành công và phát đạt không, có hương vị mạnh mẽ và ý nghĩa tốt lành?",
    "Tôi cần một hộp **trà** dễ thương để chúc mừng bạn mới thăng chức, có hương vị nhẹ nhàng và thể hiện sự vui mừng?",
    "**Trà** loại nào ý nghĩa để tặng bố nhân dịp sinh nhật, tốt cho sức khỏe tim mạch, xương khớp và tăng cường sinh lực?",
    "Tôi muốn **trà** phù hợp để gửi lời chia buồn, bạn có loại nào không quá nặng nề không?",
    "Có **trà** nào nhẹ nhàng để chúc mừng sinh nhật bé trai không, có hương vị dễ uống và tốt cho tiêu hóa của trẻ?",
    "Tôi muốn tặng **trà** cho cô giáo nhân ngày 20/11, bạn có loại nào thể hiện lòng biết ơn không?",
    "**Trà** loại nào thích hợp để gửi tặng dịp Giáng sinh, mang hương vị ấm áp, ngọt ngào và gợi nhớ không khí lễ hội?",
    "Tôi muốn mua **trà** để tặng bạn bè nhân dịp gặp mặt, có loại nào dễ uống không?",
    "Loại **trà** nào giúp thư giãn để tặng người đang bị căng thẳng?",
    "Tôi cần một loại **trà** thanh mát để chúc mừng bạn chuyển nhà mới.",
    "Bạn có **trà** để tặng người mới ốm dậy không?",
    "Tôi muốn một hộp **trà** để gửi lời cảm ơn sếp, bạn có loại nào trang nhã không?",
    "Có loại **trà** nào mang thông điệp hạnh phúc để tặng người yêu không, có hương vị ngọt ngào và ý nghĩa về tình yêu viên mãn?",
    "Tôi muốn mua **trà** để tặng đối tác trong buổi họp mặt.",
    "**Trà** loại nào phù hợp để chúc mừng đồng nghiệp hoàn thành dự án?",
    "Bạn có thể gợi ý **trà** cho dịp sinh nhật người lớn tuổi không?",
    "Tôi muốn một hộp **trà** để tặng bạn gái nhân ngày kỷ niệm.",
    "Có **trà** nào phù hợp để tặng ông bà nhân dịp đoàn tụ gia đình không?",
    "Tôi cần **trà** để gửi lời chia buồn, bạn có không?",
    "**Trà** loại nào phù hợp để tặng vào ngày Quốc tế Thiếu nhi?",
    "Tôi muốn một hộp **trà** để tặng bạn vào dịp Giáng sinh.",
    "Có loại **trà** nào giúp tăng cường trí nhớ không?",
    "Tôi muốn mua **trà** để tặng bạn trong lễ đính hôn.",
    "**Trà** loại nào phù hợp để tặng mẹ nhân dịp Ngày của Mẹ?",
    "Tôi muốn một hộp **trà** ấm áp để tặng bố nhân Ngày của Cha.",
    "Có **trà túi lọc** nào giúp tăng sức đề kháng để tặng bạn bè không?",
    "Tôi cần một hộp **trà** độc đáo để chúc mừng bạn thăng chức.",
    "Bạn có **cao, viên uống, bột, dầu xoa bóp, mật ong** không? Tôi muốn chọn một loại tốt cho sức khoẻ để làm quà."
]

chat_samples = [
    "Chào bạn! Hôm nay thời tiết thế nào nhỉ?",
    "Mùa này có gì thú vị không bạn?",
    "Hello shop",
    "Chàp shop",
    "Chào bạn! Hôm nay bạn thế nào?",
    "Bạn thích làm việc ở đây không?",
    "Bạn có thích mùa hè không?",
    "Bạn có thể kể một câu chuyện vui không?",
    "Bạn có nghe loại nhạc nào không?",
    "Bạn nghĩ gì về việc đọc sách vào buổi sáng?",
    "Bạn thích ăn món gì nhất?",
    "Bạn có kế hoạch gì cho cuối tuần không?",
    "Bạn có thích thể thao không?",
    "Bạn có hay du lịch không?",
    "Bạn thích màu gì nhất?",
    "Bạn có câu châm ngôn sống nào không?",
    "Có nơi nào bạn muốn ghé thăm không?",
    "Bạn thích hoạt động ngoài trời không?",
    "Có quyển sách nào bạn muốn giới thiệu không?",
    "Bạn có lời khuyên gì cho một cuộc sống hạnh phúc không?",
    "Bạn có thói quen nào vào buổi sáng không?",
    "Bạn có thú cưng không?",
    "Bạn thích âm nhạc loại nào?",
    "Bạn thích mùa nào nhất trong năm?",
    "Bạn có hay xem phim không?",
    "Bạn có tin vào may mắn không?",
    "Bạn có đam mê nào khác không?",
    "Có điều gì đặc biệt mà bạn muốn học không?",
    "Bạn có lời khuyên nào để có năng lượng tích cực không?",
    "Bạn thích làm gì vào thời gian rảnh?",
    "Có bài hát nào bạn yêu thích không?",
    "Bạn có thói quen tập thể dục không?",
    "Bạn có thể kể về một ngày thú vị của mình không?",
    "Bạn đã bao giờ tham gia sự kiện nào lớn chưa?",
    "Có bộ phim nào mà bạn không bao giờ quên không?",
    "Bạn có thích làm việc cùng đồng nghiệp không?",
    "Bạn có mơ ước nào chưa thực hiện không?",
    "Bạn nghĩ gì về cuộc sống thành thị?",
    "Bạn đã học được gì khi làm việc ở đây?",
    "Bạn có người thân nào cũng làm nghề này không?",
    "Có món nào bạn hay ăn vào mùa hè không?",
    "Bạn có thích mùa đông không?",
    "Có khi nào bạn gặp khách hàng khó tính không?",
    "Bạn có dự định học thêm gì không?",
    "Có gì đặc biệt bạn muốn chia sẻ hôm nay không?",
    "Bạn thích ngắm hoàng hôn hay bình minh?",
    "Bạn nghĩ sao về phong cách sống tối giản?",
    "Có sở thích nào bạn muốn khám phá không?",
    "Bạn có thích làm việc nhóm không?",
    "Bạn có hay chụp ảnh không?",
    "Bạn có tin vào số mệnh không?",
    "Bạn nghĩ gì về việc sống ở vùng quê?",
    "Có trò chơi nào bạn hay chơi không?",
    "Bạn có lời khuyên nào về sức khỏe không?",
    "Bạn có thích nấu ăn không?",
    "Có địa điểm nào bạn muốn đến thử không?",
    "Bạn có thói quen gì vào buổi tối không?",
    "Có món nào bạn đặc biệt ghét không?",
    "Bạn thích tham gia sự kiện nào nhất?",
    "Có bài hát nào làm bạn vui không?",
    "Bạn có thích sưu tầm gì không?",
    "Bạn có thích trồng cây không?",
    "Bạn có lời khuyên nào về việc giảm căng thẳng không?",
    "Bạn có thích làm việc ở đây lâu dài không?",
    "Có bộ phim nào bạn xem lại nhiều lần không?",
    "Bạn thích làm gì vào cuối tuần?",
    "Bạn có tin vào tâm linh không?",
    "Bạn có thể chia sẻ một câu nói yêu thích không?",
    "Có điều gì thú vị về công việc này không?",
    "Bạn có thường đi xem triển lãm nghệ thuật không?",
    "Bạn có nghĩ mình sẽ chuyển nghề không?",
    "Bạn thích đồ uống gì nhất?",
    "Bạn có thói quen viết nhật ký không?",
    "Bạn nghĩ sao về du lịch một mình?",
    "Có trò nào bạn thích chơi từ nhỏ không?",
    "Bạn có thường gặp khách du lịch không?",
    "Bạn có thể chia sẻ bí quyết thành công không?",
    "Bạn nghĩ sao về việc tự kinh doanh?",
    "Bạn có thích đi phượt không?",
    "Có món ăn nào bạn không thể cưỡng lại không?",
    "Bạn nghĩ gì về công việc tình nguyện?",
    "Bạn có sở thích nào mới không?",
    "Bạn có thích chụp ảnh phong cảnh không?",
    "Bạn có thể kể một bí mật nhỏ không?",
    "Có nơi nào bạn muốn quay lại nhiều lần không?",
    "Bạn có thể chia sẻ điều gì đó vui nhộn không?",
]

test_samples = [
    "Loại trà nào giúp bổ sung năng lượng để tặng đồng nghiệp?",
    "Có hộp trà nào giúp cải thiện giấc ngủ không?",
    "Tôi muốn một hộp trà thảo mộc để tặng bạn sau chuyến du lịch.",
    "Tôi cần tư vấn về trà hoa hồng tây tạng",
    "Có loại hoa nào phù hợp để chúc mừng khai trương không?",
    "Loại trà nào giúp bổ sung năng lượng để tặng đồng nghiệp?",
    "Shop ơi cho mình hỏi một chút",
    "Hello shop",
    "Xin chào, hôm nay bạn thế nào",
    "Tớ muốn tâm sự với cậu một chút",
    "Hi Shop, mình muốn tư vấn"
]